version: "3"

services:


  app:
    build: .
    container_name: fastProject4
    command: uvicorn --host 0.0.0.0 --port 8000 main:app --reload
    ports:
      - "8000:8000"

    networks:
      - fastnetwork
    restart: always


networks:
   fastnetwork:
     driver: bridge